# Generated by Django 2.1.15 on 2021-05-28 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.IntegerField(choices=[(0, 'Nuevo'), (1, 'Reprogramado')], default=0)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField(max_length=220)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Audiencia',
                'verbose_name_plural': 'Audiencias',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('codigo_caso', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=220)),
                ('estado', models.IntegerField(choices=[(0, 'En Proceso'), (1, 'Finalizado')], default=0)),
                ('tipo_pago', models.IntegerField(choices=[(0, 'Contado'), (1, 'Credito')], default=0)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
            },
        ),
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plazo', models.IntegerField()),
                ('cuota', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_fin_credito', models.DateField(null=True)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'FormaDePago',
                'verbose_name_plural': 'FormaDePagos',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=220)),
                ('correo', models.EmailField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('tipo', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=220)),
                ('cargo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saldo_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('tipo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.FormaDePago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50, unique=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rols',
            },
        ),
        migrations.CreateModel(
            name='TipoDeAbogado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=220)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Tipo de abogado',
                'verbose_name_plural': 'Tipos de abogados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDeProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=220)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Tipo de proceso',
                'verbose_name_plural': 'Tipos de procesos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='correo electronico')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('dui', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=8)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('estado_civil', models.IntegerField(choices=[(0, 'Soltero'), (1, 'Casado'), (2, 'Divorciado'), (3, 'Viudo')], default=0)),
                ('username', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Tipo_de_abogado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.TipoDeAbogado', verbose_name='Tipo De Abogado')),
            ],
            options={
                'abstract': False,
            },
            bases=('Sistema_juridico.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol_cliente', models.IntegerField(choices=[(0, 'Demandante'), (1, 'Demandado')], default=0)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'permissions': (('view_caso', 'puede ver publicaciones y categorías del blog'),),
            },
            bases=('Sistema_juridico.usuario',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='caso',
            name='tipo_de_proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.TipoDeProceso'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='codigo_caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Caso'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Institucion'),
        ),
        migrations.AddField(
            model_name='caso',
            name='id_abogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Abogado', verbose_name='Id Abogado'),
        ),
        migrations.AddField(
            model_name='caso',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Cliente', verbose_name='Id Cliente:'),
        ),
    ]
