# Generated by Django 2.1.15 on 2021-05-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Cliente'),
            preserve_default=False,
        ),
    ]
