# Generated by Django 2.1 on 2021-05-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Institucion'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='detalle',
            field=models.IntegerField(choices=[(0, 'Nuevo'), (1, 'Reprogramado')], default=0),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='hora',
            field=models.TimeField(),
        ),
    ]
