# Generated by Django 2.1 on 2021-05-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='Tipo_de_abogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.TipoDeAbogado', verbose_name='Tipo De Abogado'),
        ),
    ]
