# Generated by Django 2.1 on 2021-05-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0002_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
