# Generated by Django 2.1.15 on 2021-05-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0002_audiencia_id_cliente'),
        ('Sistema_juridico', '0002_auto_20210528_2238'),
    ]

    operations = [
    ]
