# Generated by Django 2.1 on 2021-05-30 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0002_auto_20210529_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeabogado',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-zA-Z\t]+|(^$)', message='Introduzca letras del alfabeto')]),
        ),
    ]
