# Generated by Django 2.1.15 on 2021-05-29 21:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0003_merge_20210529_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='formadepago',
            name='codigo_caso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Caso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institucion',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}$', message='Telefono invalido')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
