# Generated by Django 2.1 on 2021-05-30 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0003_auto_20210529_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeabogado',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-zA-Z ]{2,100}', message='Introduzca letras del alfabeto')]),
        ),
    ]
