# Generated by Django 2.1.15 on 2021-05-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0004_auto_20210529_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='codigo_caso',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
