# Generated by Django 2.1.15 on 2021-05-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0005_auto_20210529_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formadepago',
            name='codigo_caso',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tipo_de_pago',
        ),
        migrations.DeleteModel(
            name='FormaDePago',
        ),
    ]
