# Generated by Django 2.1 on 2021-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0005_auto_20210516_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='es_abogado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
