# Generated by Django 2.1.15 on 2021-05-30 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0006_auto_20210529_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='codigo_caso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Caso'),
            preserve_default=False,
        ),
    ]
