# Generated by Django 2.1 on 2021-05-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0006_auto_20210516_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abogado',
            name='es_abogado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='es_cliente',
        ),
    ]
