# Generated by Django 2.1 on 2021-05-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0007_auto_20210516_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='id_abogado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Abogado', verbose_name='Id Abogado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caso',
            name='id_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Cliente', verbose_name='Id Cliente'),
            preserve_default=False,
        ),
    ]
