# Generated by Django 2.1.15 on 2021-05-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0007_pago_codigo_caso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='tipo_pago',
            field=models.CharField(max_length=220),
        ),
    ]
