# Generated by Django 2.1 on 2021-05-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0008_auto_20210517_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('P', 'En Proceso'), ('F', 'Finalizado')], default=0, max_length=2),
        ),
    ]
