# Generated by Django 2.1.15 on 2021-05-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0008_auto_20210529_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='saldo_total',
        ),
    ]
