# Generated by Django 2.1.15 on 2021-05-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0009_auto_20210523_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='Tipo_de_abogado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.TipoDeAbogado', verbose_name='Tipo De Abogado'),
        ),
    ]
