# Generated by Django 2.1 on 2021-05-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0009_auto_20210518_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dui',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
