# Generated by Django 2.1.15 on 2021-05-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0010_auto_20210529_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='pago_caso',
            field=models.FloatField(max_length=220),
        ),
    ]
