# Generated by Django 2.1 on 2021-05-24 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0010_auto_20210519_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_cliente', models.IntegerField(choices=[('P', 'En Proceso'), ('F', 'Finalizado')], default=0)),
                ('codigo_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Caso', verbose_name='codigo caso')),
                ('dui_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Cliente', verbose_name='Id Cliente')),
                ('nombre_abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Abogado', verbose_name='Id Abogado')),
                ('tipo_de_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.TipoDeProceso')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administrador',
            new_name='is_abogado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_activo',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
