# Generated by Django 2.1.2 on 2021-05-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0011_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dui',
            field=models.CharField(max_length=10),
        ),
    ]
