# Generated by Django 2.1 on 2021-05-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0011_auto_20210524_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_abogado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_cliente',
        ),
    ]
