# Generated by Django 2.1 on 2021-05-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0013_auto_20210524_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='usuario_activo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
