# Generated by Django 2.1 on 2021-05-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0016_auto_20210524_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('view_caso', 'puede ver publicaciones y categorías del blog'),), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
