# Generated by Django 2.1 on 2021-05-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0018_uscitizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='uscitizen',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
