# Generated by Django 2.1 on 2021-05-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0019_uscitizen_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uscitizen',
            options={'permissions': [('can_drive', 'Can drive'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol')]},
        ),
    ]
