# Generated by Django 2.1 on 2021-05-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0020_auto_20210525_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_activo',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_administrador',
        ),
    ]
