# Generated by Django 2.1 on 2021-05-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0012_auto_20210524_1827'),
        ('Sistema_juridico', '0021_auto_20210525_0103'),
    ]

    operations = [
    ]
