# Generated by Django 2.1 on 2021-05-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0022_merge_20210525_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='codigo',
        ),
        migrations.AddField(
            model_name='reporte',
            name='codigo_caso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Caso', verbose_name='codigo caso'),
            preserve_default=False,
        ),
    ]
