# Generated by Django 2.1 on 2021-05-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0023_auto_20210525_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50, unique=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rols',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.IntegerField(choices=[(0, 'Soltero'), (1, 'Casado'), (2, 'Divorciado'), (3, 'Viudo')], default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema_juridico.Rol'),
        ),
    ]
