# Generated by Django 2.1 on 2021-05-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0024_auto_20210525_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USCitizen',
        ),
    ]
