# Generated by Django 2.1 on 2021-05-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0026_auto_20210525_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='staff',
        ),
    ]
