# Generated by Django 2.1 on 2021-05-26 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0027_auto_20210525_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dui',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{8}-\\d{1}$', message='Dui Invalido')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
