# Generated by Django 2.1 on 2021-05-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_juridico', '0029_auto_20210526_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodeproceso',
            options={'ordering': ['nombre'], 'permissions': (('can_view_tipodeproceso', 'Ver tipos de proceso'),), 'verbose_name': 'Tipo de proceso', 'verbose_name_plural': 'Tipos de procesos'},
        ),
    ]
